// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_BOOTSCREEN_H
#define UI_BOOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BootScreen
extern void ui_BootScreen_screen_init(void);
extern void ui_BootScreen_screen_destroy(void);
extern lv_obj_t *ui_BootScreen;
extern lv_obj_t *ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

