// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_BootScreen = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_BootScreen_screen_init(void)
{
ui_BootScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_BootScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_BootScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BootScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_image_create(ui_BootScreen);
lv_image_set_src(ui_Image2, &ui_img_bootscreen_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 466
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 459
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image2,300);

}

void ui_BootScreen_screen_destroy(void)
{
   if (ui_BootScreen) lv_obj_del(ui_BootScreen);

// NULL screen variables
ui_BootScreen= NULL;
ui_Image2= NULL;

}
