// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSPEEDO_H
#define UI_MAINSPEEDO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainSpeedo
extern void ui_MainSpeedo_screen_init(void);
extern void ui_MainSpeedo_screen_destroy(void);
extern void ui_event_MainSpeedo( lv_event_t * e);
extern lv_obj_t *ui_MainSpeedo;
extern lv_obj_t *ui_Odometer1;
extern lv_obj_t *ui_Odometer2;
extern lv_obj_t *ui_Odometer3;
extern lv_obj_t *ui_Odometer4;
extern lv_obj_t *ui_Odometer5;
extern lv_obj_t *ui_Odometer6;
extern lv_obj_t *ui_SpeedoNeedle;
extern lv_obj_t *ui_SpeedoValue;
extern lv_obj_t *ui_GPSDEBUG;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

