// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_MainSpeedo = NULL;lv_obj_t *ui_Odometer1 = NULL;lv_obj_t *ui_Odometer2 = NULL;lv_obj_t *ui_Odometer3 = NULL;lv_obj_t *ui_Odometer4 = NULL;lv_obj_t *ui_Odometer5 = NULL;lv_obj_t *ui_Odometer6 = NULL;lv_obj_t *ui_SpeedoNeedle = NULL;lv_obj_t *ui_SpeedoValue = NULL;lv_obj_t *ui_GPSDEBUG = NULL;
// event funtions
void ui_event_MainSpeedo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_OtherData, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_OtherData_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_OtherData, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OtherData_screen_init);
}
}

// build funtions

void ui_MainSpeedo_screen_init(void)
{
ui_MainSpeedo = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainSpeedo, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_MainSpeedo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainSpeedo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_MainSpeedo, &ui_img_gauge_background_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Odometer1 = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_Odometer1, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_Odometer1, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Odometer1, -115 );
lv_obj_set_y( ui_Odometer1, 138 );
lv_obj_set_align( ui_Odometer1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Odometer1,"-");
lv_obj_clear_flag( ui_Odometer1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Odometer1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Odometer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Odometer1, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Odometer2 = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_Odometer2, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_Odometer2, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Odometer2, -67 );
lv_obj_set_y( ui_Odometer2, 137 );
lv_obj_set_align( ui_Odometer2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Odometer2,"-");
lv_obj_clear_flag( ui_Odometer2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Odometer2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Odometer2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Odometer2, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Odometer3 = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_Odometer3, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_Odometer3, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Odometer3, -21 );
lv_obj_set_y( ui_Odometer3, 138 );
lv_obj_set_align( ui_Odometer3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Odometer3,"-");
lv_obj_clear_flag( ui_Odometer3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Odometer3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Odometer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Odometer3, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Odometer4 = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_Odometer4, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_Odometer4, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Odometer4, 27 );
lv_obj_set_y( ui_Odometer4, 138 );
lv_obj_set_align( ui_Odometer4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Odometer4,"-");
lv_obj_clear_flag( ui_Odometer4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Odometer4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Odometer4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Odometer4, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Odometer5 = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_Odometer5, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_Odometer5, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Odometer5, 74 );
lv_obj_set_y( ui_Odometer5, 138 );
lv_obj_set_align( ui_Odometer5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Odometer5,"-");
lv_obj_clear_flag( ui_Odometer5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Odometer5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Odometer5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Odometer5, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Odometer6 = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_Odometer6, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_Odometer6, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Odometer6, 122 );
lv_obj_set_y( ui_Odometer6, 138 );
lv_obj_set_align( ui_Odometer6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Odometer6,"-");
lv_obj_clear_flag( ui_Odometer6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_Odometer6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Odometer6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Odometer6, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedoNeedle = lv_img_create(ui_MainSpeedo);
lv_img_set_src(ui_SpeedoNeedle, &ui_img_gauge_needle_png);
lv_obj_set_width( ui_SpeedoNeedle, LV_SIZE_CONTENT);  /// 655
lv_obj_set_height( ui_SpeedoNeedle, LV_SIZE_CONTENT);   /// 104
lv_obj_set_x( ui_SpeedoNeedle, -124 );
lv_obj_set_y( ui_SpeedoNeedle, 359 );
lv_obj_clear_flag( ui_SpeedoNeedle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(ui_SpeedoNeedle,522,52);
lv_img_set_angle(ui_SpeedoNeedle,2480);
lv_img_set_zoom(ui_SpeedoNeedle,150);

ui_SpeedoValue = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_SpeedoValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedoValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedoValue, 6 );
lv_obj_set_y( ui_SpeedoValue, 222 );
lv_obj_set_align( ui_SpeedoValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedoValue,"0");
lv_obj_clear_flag( ui_SpeedoValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SpeedoValue, lv_color_hex(0x383112), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedoValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedoValue, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GPSDEBUG = lv_label_create(ui_MainSpeedo);
lv_obj_set_width( ui_GPSDEBUG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GPSDEBUG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GPSDEBUG, 2 );
lv_obj_set_y( ui_GPSDEBUG, -179 );
lv_obj_set_align( ui_GPSDEBUG, LV_ALIGN_CENTER );
lv_label_set_text(ui_GPSDEBUG,"");
lv_obj_clear_flag( ui_GPSDEBUG, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_GPSDEBUG, lv_color_hex(0xEA0A38), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_GPSDEBUG, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_GPSDEBUG, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GPSDEBUG, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GPSDEBUG, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MainSpeedo, ui_event_MainSpeedo, LV_EVENT_ALL, NULL);

}

void ui_MainSpeedo_screen_destroy(void)
{
   if (ui_MainSpeedo) lv_obj_del(ui_MainSpeedo);

// NULL screen variables
ui_MainSpeedo= NULL;
ui_Odometer1= NULL;
ui_Odometer2= NULL;
ui_Odometer3= NULL;
ui_Odometer4= NULL;
ui_Odometer5= NULL;
ui_Odometer6= NULL;
ui_SpeedoNeedle= NULL;
ui_SpeedoValue= NULL;
ui_GPSDEBUG= NULL;

}
