// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_OtherData = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_AfrV = NULL;lv_obj_t *ui_TempV = NULL;lv_obj_t *ui_SpeedV = NULL;lv_obj_t *ui_SpeedD = NULL;lv_obj_t *ui_AfrD = NULL;lv_obj_t *ui_TempD = NULL;
// event funtions
void ui_event_OtherData( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MainSpeedo, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainSpeedo_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MainSpeedo, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MainSpeedo_screen_init);
}
}

// build funtions

void ui_OtherData_screen_init(void)
{
ui_OtherData = lv_obj_create(NULL);
lv_obj_clear_flag( ui_OtherData, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OtherData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OtherData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_OtherData);
lv_img_set_src(ui_Image1, &ui_img_gauge_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 800
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 800
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_AfrV = lv_label_create(ui_OtherData);
lv_obj_set_width( ui_AfrV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AfrV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AfrV, -141 );
lv_obj_set_y( ui_AfrV, -74 );
lv_obj_set_align( ui_AfrV, LV_ALIGN_CENTER );
lv_label_set_text(ui_AfrV,"14.7");
lv_obj_clear_flag( ui_AfrV, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_AfrV, lv_color_hex(0xF2E6B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AfrV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AfrV, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempV = lv_label_create(ui_OtherData);
lv_obj_set_width( ui_TempV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempV, 134 );
lv_obj_set_y( ui_TempV, -77 );
lv_obj_set_align( ui_TempV, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempV,"-");
lv_obj_clear_flag( ui_TempV, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_TempV, lv_color_hex(0xF2E6B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempV, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedV = lv_label_create(ui_OtherData);
lv_obj_set_width( ui_SpeedV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedV, -1 );
lv_obj_set_y( ui_SpeedV, 143 );
lv_obj_set_align( ui_SpeedV, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedV,"0");
lv_obj_clear_flag( ui_SpeedV, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SpeedV, lv_color_hex(0xF2E6B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedV, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedD = lv_img_create(ui_OtherData);
lv_img_set_src(ui_SpeedD, &ui_img_needle_no_shadow65_png);
lv_obj_set_width( ui_SpeedD, LV_SIZE_CONTENT);  /// 12
lv_obj_set_height( ui_SpeedD, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_SpeedD, 0 );
lv_obj_set_y( ui_SpeedD, 315 );
lv_obj_set_align( ui_SpeedD, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpeedD, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(ui_SpeedD,9,-295);
lv_img_set_angle(ui_SpeedD,-548);

ui_AfrD = lv_img_create(ui_OtherData);
lv_img_set_src(ui_AfrD, &ui_img_needle_no_shadow65_png);
lv_obj_set_width( ui_AfrD, LV_SIZE_CONTENT);  /// 12
lv_obj_set_height( ui_AfrD, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_AfrD, 0 );
lv_obj_set_y( ui_AfrD, 315 );
lv_obj_set_align( ui_AfrD, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AfrD, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(ui_AfrD,9,-295);
lv_img_set_angle(ui_AfrD,1312);

ui_TempD = lv_img_create(ui_OtherData);
lv_img_set_src(ui_TempD, &ui_img_needle_no_shadow65_png);
lv_obj_set_width( ui_TempD, LV_SIZE_CONTENT);  /// 12
lv_obj_set_height( ui_TempD, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_TempD, 0 );
lv_obj_set_y( ui_TempD, 315 );
lv_obj_set_align( ui_TempD, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TempD, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_pivot(ui_TempD,9,-295);
lv_img_set_angle(ui_TempD,2747);

lv_obj_add_event_cb(ui_OtherData, ui_event_OtherData, LV_EVENT_ALL, NULL);

}

void ui_OtherData_screen_destroy(void)
{
   if (ui_OtherData) lv_obj_del(ui_OtherData);

// NULL screen variables
ui_OtherData= NULL;
ui_Image1= NULL;
ui_AfrV= NULL;
ui_TempV= NULL;
ui_SpeedV= NULL;
ui_SpeedD= NULL;
ui_AfrD= NULL;
ui_TempD= NULL;

}
