// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_OtherData = NULL;lv_obj_t *ui_AFRARC = NULL;lv_obj_t *ui_AFRLabel = NULL;lv_obj_t *ui_AFRValue = NULL;
// event funtions
void ui_event_OtherData( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_MainSpeedo, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainSpeedo_screen_init);
}
}

// build funtions

void ui_OtherData_screen_init(void)
{
ui_OtherData = lv_obj_create(NULL);
lv_obj_clear_flag( ui_OtherData, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OtherData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OtherData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AFRARC = lv_arc_create(ui_OtherData);
lv_obj_set_width( ui_AFRARC, 500);
lv_obj_set_height( ui_AFRARC, 500);
lv_obj_set_align( ui_AFRARC, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AFRARC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_arc_set_range(ui_AFRARC, 100,194);
lv_arc_set_value(ui_AFRARC, 147);

ui_AFRLabel = lv_label_create(ui_OtherData);
lv_obj_set_width( ui_AFRLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AFRLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AFRLabel, 0 );
lv_obj_set_y( ui_AFRLabel, 100 );
lv_obj_set_align( ui_AFRLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AFRLabel,"AFR");
lv_obj_clear_flag( ui_AFRLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_AFRLabel, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AFRLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AFRLabel, &ui_font_DIN_1451_Mittelschrift_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AFRValue = lv_label_create(ui_OtherData);
lv_obj_set_width( ui_AFRValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AFRValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AFRValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_AFRValue,"14.7");
lv_obj_clear_flag( ui_AFRValue, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_AFRValue, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AFRValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AFRValue, &ui_font_DIN_1451__96, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_OtherData, ui_event_OtherData, LV_EVENT_ALL, NULL);

}

void ui_OtherData_screen_destroy(void)
{
   if (ui_OtherData) lv_obj_del(ui_OtherData);

// NULL screen variables
ui_OtherData= NULL;
ui_AFRARC= NULL;
ui_AFRLabel= NULL;
ui_AFRValue= NULL;

}
