// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OTHERDATA_H
#define UI_OTHERDATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OtherData
extern void ui_OtherData_screen_init(void);
extern void ui_OtherData_screen_destroy(void);
extern void ui_event_OtherData( lv_event_t * e);
extern lv_obj_t *ui_OtherData;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_AfrV;
extern lv_obj_t *ui_TempV;
extern lv_obj_t *ui_SpeedV;
extern lv_obj_t *ui_SpeedD;
extern lv_obj_t *ui_AfrD;
extern lv_obj_t *ui_TempD;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

