// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#ifndef UI_RPMAFR_H
#define UI_RPMAFR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RPMAFR
extern void ui_RPMAFR_screen_init(void);
extern void ui_RPMAFR_screen_destroy(void);
extern void ui_event_RPMAFR( lv_event_t * e);
extern lv_obj_t *ui_RPMAFR;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_AfrV2;
extern lv_obj_t *ui_SpeedV2;
extern lv_obj_t *ui_RpmD;
extern lv_obj_t *ui_RpmV;
extern lv_obj_t *ui_TimeV2;
extern lv_obj_t *ui_AFRStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

