// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_RPMAFR = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_AfrV2 = NULL;lv_obj_t *ui_SpeedV2 = NULL;lv_obj_t *ui_RpmD = NULL;lv_obj_t *ui_RpmV = NULL;lv_obj_t *ui_TimeV2 = NULL;lv_obj_t *ui_AFRStatus = NULL;
// event funtions
void ui_event_RPMAFR( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_OtherData, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_OtherData_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_Settings, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Settings_screen_init);
}
}

// build funtions

void ui_RPMAFR_screen_init(void)
{
ui_RPMAFR = lv_obj_create(NULL);
lv_obj_remove_flag( ui_RPMAFR, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RPMAFR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RPMAFR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_image_create(ui_RPMAFR);
lv_image_set_src(ui_Image3, &ui_img_tacho_rpm_dial_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 800
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 800
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_AfrV2 = lv_label_create(ui_RPMAFR);
lv_obj_set_width( ui_AfrV2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AfrV2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AfrV2, -115 );
lv_obj_set_y( ui_AfrV2, 171 );
lv_obj_set_align( ui_AfrV2, LV_ALIGN_CENTER );
lv_label_set_text(ui_AfrV2,"14.7");
lv_obj_remove_flag( ui_AfrV2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_AfrV2, lv_color_hex(0xF2E6B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AfrV2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AfrV2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AfrV2, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedV2 = lv_label_create(ui_RPMAFR);
lv_obj_set_width( ui_SpeedV2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedV2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedV2, 98 );
lv_obj_set_y( ui_SpeedV2, 172 );
lv_obj_set_align( ui_SpeedV2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedV2,"0");
lv_obj_remove_flag( ui_SpeedV2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SpeedV2, lv_color_hex(0xF2E6B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedV2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SpeedV2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedV2, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RpmD = lv_image_create(ui_RPMAFR);
lv_image_set_src(ui_RpmD, &ui_img_needle_no_shadow65_png);
lv_obj_set_width( ui_RpmD, LV_SIZE_CONTENT);  /// 12
lv_obj_set_height( ui_RpmD, LV_SIZE_CONTENT);   /// 42
lv_obj_set_x( ui_RpmD, 9 );
lv_obj_set_y( ui_RpmD, 290 );
lv_obj_set_align( ui_RpmD, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_RpmD, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_image_set_pivot(ui_RpmD,0,-270);
lv_image_set_rotation(ui_RpmD,710);

ui_RpmV = lv_label_create(ui_RPMAFR);
lv_obj_set_width( ui_RpmV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RpmV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RpmV, -1 );
lv_obj_set_y( ui_RpmV, -65 );
lv_obj_set_align( ui_RpmV, LV_ALIGN_CENTER );
lv_label_set_text(ui_RpmV,"2200");
lv_obj_remove_flag( ui_RpmV, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_RpmV, lv_color_hex(0xF2E6B0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RpmV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RpmV, &ui_font_DSGE7_Classic_80, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeV2 = lv_label_create(ui_RPMAFR);
lv_obj_set_width( ui_TimeV2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeV2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeV2, 3 );
lv_obj_set_y( ui_TimeV2, 30 );
lv_obj_set_align( ui_TimeV2, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeV2,"16:45");
lv_obj_set_style_text_color(ui_TimeV2, lv_color_hex(0xF80303), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeV2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeV2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeV2, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AFRStatus = lv_label_create(ui_RPMAFR);
lv_obj_set_width( ui_AFRStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AFRStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AFRStatus, -89 );
lv_obj_set_y( ui_AFRStatus, 252 );
lv_obj_set_align( ui_AFRStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_AFRStatus,"Heating\n360C");
lv_obj_set_style_text_color(ui_AFRStatus, lv_color_hex(0xF60606), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AFRStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AFRStatus, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AFRStatus, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_RPMAFR, ui_event_RPMAFR, LV_EVENT_ALL, NULL);

}

void ui_RPMAFR_screen_destroy(void)
{
   if (ui_RPMAFR) lv_obj_del(ui_RPMAFR);

// NULL screen variables
ui_RPMAFR= NULL;
ui_Image3= NULL;
ui_AfrV2= NULL;
ui_SpeedV2= NULL;
ui_RpmD= NULL;
ui_RpmV= NULL;
ui_TimeV2= NULL;
ui_AFRStatus= NULL;

}
