// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Settings = NULL;lv_obj_t *ui_DemoSwitch = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions
void ui_event_Settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_RPMAFR, LV_SCREEN_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_RPMAFR_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_MainSpeedo, LV_SCREEN_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_MainSpeedo_screen_init);
}
}

void ui_event_DemoSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      ChangeDemoMode( e );
}
}

// build funtions

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DemoSwitch = lv_switch_create(ui_Settings);
lv_obj_set_width( ui_DemoSwitch, 261);
lv_obj_set_height( ui_DemoSwitch, 115);
lv_obj_set_x( ui_DemoSwitch, 0 );
lv_obj_set_y( ui_DemoSwitch, 178 );
lv_obj_set_align( ui_DemoSwitch, LV_ALIGN_CENTER );

ui_Label1 = lv_label_create(ui_Settings);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -9 );
lv_obj_set_y( ui_Label1, 90 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Demo Mode");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_DemoSwitch, ui_event_DemoSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
   if (ui_Settings) lv_obj_del(ui_Settings);

// NULL screen variables
ui_Settings= NULL;
ui_DemoSwitch= NULL;
ui_Label1= NULL;

}
